### ISSUE TITLE
building out with Solr4

### ISSUE THREAD

**Issue by mgrbyte** [collective/collective.recipe.solrinstance#32]
We've encountered the following issue:

The first time you run buildout, parts/solr-instance and parts/solr-download are created
bin/solr-instance fg will fail to start properly with an error similar to: 
1937 [coreLoadExecutor-5-thread-1] ERROR org.apache.solr.core.CoreContainer  – Unable to create core: collection1

The solution is to rm -rf parts/solr-instance and re-buildout.

Here's what I think is happening:

When buildout executes its parts, solr-download does not yet exist, thus the recipe is_solr_4 method returns False.

This can be verified by removing the solr-download directory, re-running buildout, causing the same error as encountered in a first time buildout of a project configured with this recipe.

Currently we work around this by running buildout twice, removing parts/solr-instance after the first buildout invokation.

We a more permanent solution be to parse the URL/buildout recipe section for the version of solr, rather than relying upon the existence of a directory (is_solr_4) ?

**Comment by saily** [comment]
See: #36 and #39. 

The update method does not remove the `solr-instance` directory. I see no disadvantage to always remove and rebuild when running buildout, since the index is stored elsewhere. Do you agree?

**Comment by mgrbyte** [comment]
FWIW, I agree

**Comment by saily** [comment]
Ah, you're talking about the `is_solr_4` method which just tried to detect the `collection1` folder to decide wether to use Solr 4 or Solr 3 template folders. This has been refactored in #40 so this is obsolete.

**Comment by saily** [comment]
Should have been fixed during refactoring in #40.
