### ISSUE TITLE
Remove single core support

### ISSUE THREAD

**Issue by saily** [collective/collective.recipe.solrinstance#39]
I found following statement in [Solr wiki](https://wiki.apache.org/solr/ConfiguringSolr): *Support for single-core mode is likely to be removed in version 5.0.*

Removing single core support would make things a lot easier and more generic to test. I'd recommend to implement single core mode as a multicore setup with just one `default` core preconfigured. if `cores` attribute is missing (for legacy setups) it would be necessary to read from single core data dir in `var/solr` directly to not confuse users if they did not pin their recipe version in production setups. For now i see no disadvantage.

I'm also thinking about completly removing Solr 3.5 support from the recipe. 
What do you guys think about?

**Comment by jensens** [comment]
+1 removing old solr support is perfectly fine as long all housekeeping was done before: branch away old version, increase major version, document it.

**Comment by saily** [comment]
Single core support dropped for Solr 5 in #40.
