### ISSUE TITLE
Why was the single core setup removed?

### ISSUE THREAD

**Issue by tisto** [collective/collective.recipe.solrinstance#44]
For large deployments multi-core setup sometimes makes sense. Though, while working on making c.solr work with the latest c.r.solrinstance I ran into quite a few issues. I was wondering why we did this move to force multi core setups? 

I'm familiar with working with multiple cores, so I can handle that. Though, I'm afraid that's not the case for the regular integrators. This will break most Solr setups and we will not be able to handle everything with upgrade steps in c.solr (we have to amend the Solr base because we currently do not care about cores).

If there is a good reason for dropping mc supports, that's ok with me. Though, we should keep in mind that there is a considerable upgrade effort necessary for most integrators.

**Comment by tomgross** [comment]
Single core setup was removed in Solr. https://cwiki.apache.org/confluence/display/solr/Moving+to+the+New+solr.xml+Format
