### ISSUE TITLE
Log4j properties file stored to wrong location

### ISSUE THREAD

**Issue by do3cc** [collective/collective.recipe.solrinstance#45]
Solr does not look at etc/log4j.properties for logging, it looks at resources/log4j.properties.

**Comment by gforcada** [comment]
@do3cc that's fixed with your *last* (as in half a year ago) commit? https://github.com/collective/collective.recipe.solrinstance/commit/6a7ada2641c575108600dfd70e97f0a5b85b6659

**Comment by do3cc** [comment]
I don't REALLY know. right now sentry logging in solr is not working so something is not correctly working.
The branch itself, we are using it but it contains changes that may be unwanted. Unfortunately, I don't have time to work on this atm.
I believe the next time I work on it, I remove most of the test setup changes and change our own settings to use solr provided by docker.
Sorry, that does not help you a lot right now :-(

**Comment by mauritsvanrees** [comment]
The mentioned fix does the trick.  In other words:
- With latest 6.0.0b3 (1.5 years old) every search is logged, because INFO level is logged.
- With the master branch I only see the warnings.
